version: '3.3'

services:
  
  bank:
    container_name: VibeBot-Bank
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: bank
    volumes:
      - ./config.ini:/app/config/config.ini:ro
      - ./data.json:/app/config/data.json:rw
      - ./output.log:/app/config/bank.log:rw
    network_mode: host

  chameleon:
    container_name: VibeBot-Chameleon
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: chameleon
    volumes:
      - ./config.ini:/app/config/config.ini:ro
      - ./output.log:/app/config/chameleon.log:rw
    depends_on:
      - bank
    network_mode: host

  shop:
    container_name: VibeBot-Shop
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: shop
    volumes:
      - ./config.ini:/app/config/config.ini:ro
      - ./output.log:/app/config/shop.log:rw
    depends_on:
      - bank
    network_mode: host

  gambling:
    container_name: VibeBot-Croupier
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: gambling
    volumes:
      - ./config.ini:/app/config/config.ini:ro
      - ./output.log:/app/config/croupier.log:rw
      - ./data-bets.json:/app/config/data-bets.json:rw
    depends_on:
      - bank
    network_mode: host

  polling:
    container_name: VibeBot-Polling
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: polling
    volumes:
      - ./config.ini:/app/config/config.ini:ro
      - ./output.log:/app/config/polling.log:rw
      - ./data-polling.json:/app/config/data-polling.json:rw
    depends_on:
      - bank
    network_mode: host

    # Use this line to disable a bot
    # entrypoint: ["echo", "Bot 'polling' disabled"]
