version: '3.3'

services:
  
  bank:
    container_name: VibeBot-Bank
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: bank
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./data.json:/app/data.json:rw
      - ./output.log:/app/bank.log:rw
    network_mode: host

  chameleon:
    container_name: VibeBot-Chameleon
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        bot: chameleon
    volumes:
      - ./config.ini:/app/config.ini:ro
      - ./output.log:/app/chameleon.log:rw
    depends_on:
      - bank
    network_mode: host

#  shop:
#    container_name: VibeBot-Shop
#    build:
#      dockerfile: ./Dockerfile
#      context: .
#      args:
#        bot: shop
#    volumes:
#      - ./config.ini:/app/config.ini:ro
#      - ./output.log:/app/shop.log:rw
#    depends_on:
#      - bank
#    network_mode: host

