name: Docker Build Bots Image

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    environment: main
    steps:
    - 
      name: Get current time
      uses: josStorer/get-current-time@v2
      id: time
      with:
        format: YYYYMMDD-HHmm
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - 
      name: Create context
      run: |
        docker context create builder
        docker context use builder
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        endpoint: builder
        config-inline: |
          [worker.oci]
          max-parallelism = 2
    - 
      name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm/v7
        tags: ${{ secrets.REGISTRY_URL }}/discordbot:latest,${{ secrets.REGISTRY_URL }}/discordbot:${{ steps.time.outputs.formattedTime }}
