name: Docker Image CI - Manual

on: 
  workflow_call:

jobs:
  buildx:
    if: github.event.review.state == 'approved'
    #runs-on: ubuntu-latest
    runs-on: [self-hosted]
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.playforms }}
