name: Docker Image CI - Manual

on: 
  workflow_dispatch:

jobs:
  buildx:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted]
    environment: main
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - 
      name: Set up Docker Buildx
      run:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          # - docker buildx rm builder || true
        - docker buildx create --name builder --driver docker-container --use
        - docker buildx build --push --platform linux/arm/v7,linux/amd64,linux/arm64 --tag registry.coombszy.com/vibebot:latest .
    - 
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.playforms }}
